import { Routes } from '@angular/router';
import { Documentation } from './documentation/documentation';
import { Crud } from './crud/crud';
import { Empty } from './empty/empty';
import { HotelesCrudComponent } from './hotel/hotel';
import { HabitacionesCrudComponent } from './habitacion/habitacion';
import { ReservasCrudComponent } from './reserva/reserva';
import { FacturasHotelComponent } from './factura-hotel/factura-hotel';
import { RestaurantesCrudComponent } from './restaurante/restaurante/restaurante';
import { PlatillosCrudComponent } from './restaurante/platillo-crud/platillo-crud';
import { CuentasCrudComponent } from './restaurante/cuentas-crud/cuentas-crud';
import { FacturasRestComponent } from './restaurante/facturas-res/facturas-res';
import { RegisterComponent } from './auth/register/register';
//import { ReviewPlatilloComponent } from './reviews/review-platillo/review-platillo';
import { ReviewHotelComponent } from './reviews/review-hotel/review-hotel';
import { ReviewsPlatillosPorCuentaComponent } from './reviews/review-platillo/review-platillo';
import { PopularRestauranteComponent } from './reportes/popular-restaurante/popular-restaurante';
import { PopularHabitacionComponent } from './reportes/popular-habitacion/popular-habitacion';
import { IngresosRestauranteComponent } from './reportes/ingresos-restaurante/ingresos-restaurante';
import { ReportesDashboardComponent } from './reportes/reportes-dashboard/reportes-dashboard';

export default [
    { path: 'documentation', component: Documentation },
    { path: 'crud', component: Crud },
    { path: 'empty', component: Empty },
    { path: 'hotel', component: HotelesCrudComponent },
    { path: 'habitacion', component: HabitacionesCrudComponent },
    { path: 'reserva', component: ReservasCrudComponent },
    { path: 'facturas', component: FacturasHotelComponent },
    { path: 'restaurantes', component: RestaurantesCrudComponent },
    { path: 'restaurantes/platillos', component: PlatillosCrudComponent },
    { path: 'restaurantes/cuenta', component: CuentasCrudComponent },
    { path: 'restaurantes/facturas-rest', component: FacturasRestComponent },
    { path: 'register', component: RegisterComponent },
    { path: 'review-platillo', component: ReviewsPlatillosPorCuentaComponent },
    { path: 'review-hotel', component: ReviewHotelComponent },
    { path: 'popular-rest', component: PopularRestauranteComponent },
    { path: 'popular-habitacion', component: PopularHabitacionComponent },
    { path: 'reportes', component: ReportesDashboardComponent },
    { path: 'ingresos-rest', component: IngresosRestauranteComponent },
    { path: '**', redirectTo: '/notfound' }
] as Routes;
